name: ci
on:
  pull_request:
    branches: [ main, feature/*, hotfix/* ]
  push:
    branches: [ main, feature/*, hotfix/* ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - uses: ./.github/actions/build

    - run: npm run lint
      shell: bash
      working-directory: templates

    - run: npm test
      shell: bash
      working-directory: templates

    - run: choco install wkhtmltopdf
      if: matrix.os == 'windows-latest'

    - run: echo "DOTNET_DbgEnableMiniDump=1" >> $GITHUB_ENV
      if: matrix.os == 'ubuntu-latest'

    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- docs/docfx.json
    - run: dotnet run -c Release --no-build -f net8.0 --project src/docfx -- samples/seed/docfx.json --output docs/_site/seed

    - uses: actions/upload-pages-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        path: docs/_site
  
    - uses: actions/upload-artifact@v3
      if: ${{ failure() && matrix.os == 'ubuntu-latest' }}
      with:
        name: dump
        path: /tmp/coredump*
  
  publish-docs:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: actions/deploy-pages@v2
